RoomId: myroom #roomId will be given from the referee
Role: player2 #player1/player2
Team: TeamFang
TeamNo.: "2"

link1_length:  "0.1" # min 0.045
link2_length:  "0.15" # min 0.05125
link3_length:  "0.2" # min 0.0115

theta_joint2: "90" #degree