<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- parameter -->
  <xacro:include filename="$(find robot_description)/urdf/parameter_v2.xacro"/>

  <link name="world"/>

  <!-- world -->
  <xacro:include filename="$(find robot_description)/urdf/world.xacro"/>

  <!-- robot -->
  <joint name="jointX" type="prismatic">
    <origin xyz="0.0 0.0 0.2" rpy="0.0 0.0 0.0"/>
    <parent link="world"/>
    <child link="linkX"/>
    <axis xyz="1 0 0"/>
    <limit lower="-0.40" upper="0.40" effort="0.0" velocity="0.0"/>
    <dynamics damping="0" friction="1000"/>
  </joint>

  <link name="linkX">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia
        ixx="0.01" ixy="0.0" ixz="0.0"
        iyy="0.01" iyz="0.0"
        izz="0.01"/>
    </inertial>
  </link>

  <joint name="jointY" type="prismatic">
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    <parent link="linkX"/>
    <child link="linkY"/>
    <axis xyz="0 1 0"/>
    <limit lower="-0.40" upper="0.40" effort="0.0" velocity="0.0"/>
    <dynamics damping="0" friction="1000"/>
  </joint>

  <link name="linkY">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia
        ixx="0.01" ixy="0.0" ixz="0.0"
        iyy="0.01" iyz="0.0"
        izz="0.01"/>
    </inertial>
  </link>

  <joint name="jointZ" type="prismatic">
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    <parent link="linkY"/>
    <child link="link0"/>
    <axis xyz="0 0 1"/>
    <limit lower="0" upper="0.40" effort="0.0" velocity="0.0"/>
    <dynamics damping="0" friction="1000"/>
  </joint>

  <link name="link0">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file:///$(find robot_description)/meshes/link_base.STL"/>
      </geometry>
      <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia
        ixx="0.01" ixy="0.0" ixz="0.0"
        iyy="0.01" iyz="0.0"
        izz="0.01"/>
    </inertial>
  </link>

  <joint name="joint1" type="revolute">
    <parent link="link0"/>
    <child link="link1"/>
    <origin rpy="0 0 0" xyz="0 0 0.04"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14" upper="3.14" effort="1000" velocity="1000"/>
    <dynamics damping="0" friction="1000"/>
  </joint>

  <link name="link1">
    <visual>
      <origin xyz="0 0 ${LINK1_LENGTH/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.04" length="${LINK1_LENGTH}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${LINK1_LENGTH/2}" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia
        ixx="0.01" ixy="0.0" ixz="0.0"
        iyy="0.01" iyz="0.0"
        izz="0.01"/>
    </inertial>
  </link>

  <joint name="fixed_link1" type="fixed">
    <parent link="link1"/>
    <child link="link_joint2-1"/>
  </joint>

  <link name="link_joint2-1">
    <visual>
      <origin xyz="0 0 ${LINK1_LENGTH+0.045}" rpy="0 ${-pi/2} 0"/>
      <geometry>
        <mesh filename="file:///$(find robot_description)/meshes/joint_2-1.STL"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${LINK1_LENGTH+0.045}" rpy="0 ${-pi/2} 0"/>
      <mass value="0.5"/>
      <inertia
        ixx="0.01" ixy="0.0" ixz="0.0"
        iyy="0.01" iyz="0.0"
        izz="0.01"/>
    </inertial>
  </link>

  <joint name="joint2" type="fixed">
    <parent link="link_joint2-1"/>
    <child link="link_joint2-2" />
    <origin rpy="${pi} ${pi/2} 0" xyz="0.04 0 ${LINK1_LENGTH+0.045}"/>
    <dynamics damping="0" friction="1000"/>
  </joint>

  <link name="link_joint2-2">
    <visual>
      <origin xyz="0 0 -0.04" rpy="0 0 ${pi+THETA_JOINT4_RAD}"/>
      <geometry>
        <mesh filename="file:///$(find robot_description)/meshes/joint_2-2.STL"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0.04" rpy="0 0 ${pi+THETA_JOINT4_RAD}"/>
      <mass value="0.01"/>
      <inertia
        ixx="0.01" ixy="0.0" ixz="0.0"
        iyy="0.01" iyz="0.0"
        izz="0.01"/>
    </inertial>
  </link>

  <joint name="fixed_joint2-2" type="fixed">
    <parent link="link_joint2-2"/>
    <child link="link2"/>
    <origin rpy="0 ${-pi/2} ${-pi+THETA_JOINT4_RAD}" xyz="${(((-LINK2_LENGTH/2)-0.085)*sin((pi/2)-THETA_JOINT4_RAD))} ${((-LINK2_LENGTH/2)-0.085)*cos((pi/2)-THETA_JOINT4_RAD)} -0.04"/>
  </joint>

  <link name="link2">

    <visual>
      <origin xyz="0 0 0.04" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.04" length="${LINK2_LENGTH}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0.04 0 0.04" rpy="0 0 0"/>
      <mass value="0.0"/>
      <inertia
        ixx="0.01" ixy="0.0" ixz="0.0"
        iyy="0.01" iyz="0.0"
        izz="0.01"/>
    </inertial>
  </link>

  <joint name="fixed_joint4" type="fixed">
    <parent link="link2"/>
    <child link="link_joint4"/>
    <origin rpy="${pi} 0 0" xyz="0 0 ${(-LINK2_LENGTH/2)+0.04}"/>
  </joint>

  <link name="link_joint4">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file:///$(find robot_description)/meshes/joint_4.STL"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
        ixx="0.01" ixy="0.0" ixz="0.0"
        iyy="0.01" iyz="0.0"
        izz="0.01"/>
    </inertial>
  </link>

  <joint name="fixed_joint5" type="fixed">
    <parent link="link2"/>
    <child link="link_joint5"/>
    <origin rpy="0 ${pi/2} 0" xyz="0 0 ${(-LINK2_LENGTH/2)-0.005-0.00625}"/>
  </joint>

  <link name="link_joint5">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file:///$(find robot_description)/meshes/joint_5.STL"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
        ixx="0.01" ixy="0.0" ixz="0.0"
        iyy="0.01" iyz="0.0"
        izz="0.01"/>
    </inertial>
  </link>

  <joint name="joint5" type="revolute">
    <parent link="link_joint5"/>
    <child link="link5" />
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-1" upper="1" effort="1000" velocity="1000"/>
    <dynamics damping="0" friction="1000"/>
  </joint>

  <link name="link5">
    <visual>
      <origin xyz="${(LINK5_LENGTH/2)-0.015} 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder radius="0.03" length="${LINK5_LENGTH}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia
        ixx="0.01" ixy="0.0" ixz="0.0"
        iyy="0.01" iyz="0.0"
        izz="0.01"/>
    </inertial>
  </link>

  <joint name="joint6" type="revolute">
    <parent link="link5"/>
    <child link="link_hook" />
    <origin rpy="0 ${pi/2} 0" xyz="${(LINK5_LENGTH)-0.015+0.0265} 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14" upper="3.14" effort="1000" velocity="1000"/>
    <dynamics damping="0" friction="1000"/>
  </joint>

  <link name="link_hook">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file:///$(find robot_description)/meshes/link_hook.STL"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
        ixx="0.01" ixy="0.0" ixz="0.0"
        iyy="0.01" iyz="0.0"
        izz="0.01"/>
    </inertial>
  </link>

  <joint name="fixed_collision_box1" type="fixed">
    <parent link="link_hook"/>
    <child link="collision_box_1"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </joint>

  <link name="collision_box_1">
    <inertial>
      <origin xyz="0 0 -0.0125" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia
        ixx="0.01" ixy="0.0" ixz="0.0"
        iyy="0.01" iyz="0.0"
        izz="0.01"/>
    </inertial>

    <collision>
      <origin xyz="0 0 -0.0125" rpy="0 0 0"/>
      <geometry>
        <box size="0.08 0.08 0.025"/>
      </geometry> 
    </collision>
  </link>

  <joint name="fixed_collision_box2" type="fixed">
    <parent link="collision_box_1"/>
    <child link="collision_box_2"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </joint>

  <link name="collision_box_2">
    <inertial>
      <origin xyz="-0.05 0 0.035" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia
        ixx="0.01" ixy="0.0" ixz="0.0"
        iyy="0.01" iyz="0.0"
        izz="0.01"/>
    </inertial>

    <collision>
      <origin xyz="-0.05 0 0.035" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.08 0.11"/>
      </geometry> 
    </collision>
  </link>

  <joint name="fixed_collision_box3" type="fixed">
    <parent link="collision_box_2"/>
    <child link="collision_box_3"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </joint>

  <link name="collision_box_3">
    <inertial>
      <origin xyz="-0.01 0 0.1" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia
        ixx="0.01" ixy="0.0" ixz="0.0"
        iyy="0.01" iyz="0.0"
        izz="0.01"/>
    </inertial>

    <collision>
      <origin xyz="-0.01 0 0.1" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.08 0.02"/>
      </geometry> 
    </collision>
  </link>

  <!-- gazebo plugin -->
  <xacro:include filename="$(find robot_description)/urdf/gazebo_v2.xacro"/>

</robot>