<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- <xacro:include filename="$(find robot_description)/urdf/parameter_v2.xacro"/>

  <link name="world"/> -->
  
  <joint name="fixed_shelf" type="fixed">
    <parent link="world"/>
    <child link="shelf"/>
  </joint>

  <link name="shelf">
    <visual>
      <origin xyz="0 ${shelf_dist+0.1} 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file:///$(find robot_description)/meshes/shelf.STL"/>
      </geometry>
      <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 ${shelf_dist+0.1} 0" rpy="0 0 0"/>
      <mass value="5.0"/>
      <inertia
        ixx="0.01" ixy="0.0" ixz="0.0"
        iyy="0.01" iyz="0.0"
        izz="0.01"/>
    </inertial>

    <collision>
      <origin xyz="0 ${shelf_dist+0.1} 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file:///$(find robot_description)/meshes/shelf.STL"/>
      </geometry> 
    </collision>
  </link> 

  <!-- <gazebo reference="shelf">
    <material>Gazebo/White</material>
  </gazebo> -->
</robot>